// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: message_to_engine.proto

package protobuf_generated_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageToEngineType int32

const (
	MessageToEngineType_CREATE_ORDER    MessageToEngineType = 0
	MessageToEngineType_CANCEL_ORDER    MessageToEngineType = 1
	MessageToEngineType_ON_RAMP         MessageToEngineType = 2
	MessageToEngineType_GET_DEPTH       MessageToEngineType = 3
	MessageToEngineType_GET_OPEN_ORDERS MessageToEngineType = 4
)

// Enum value maps for MessageToEngineType.
var (
	MessageToEngineType_name = map[int32]string{
		0: "CREATE_ORDER",
		1: "CANCEL_ORDER",
		2: "ON_RAMP",
		3: "GET_DEPTH",
		4: "GET_OPEN_ORDERS",
	}
	MessageToEngineType_value = map[string]int32{
		"CREATE_ORDER":    0,
		"CANCEL_ORDER":    1,
		"ON_RAMP":         2,
		"GET_DEPTH":       3,
		"GET_OPEN_ORDERS": 4,
	}
)

func (x MessageToEngineType) Enum() *MessageToEngineType {
	p := new(MessageToEngineType)
	*p = x
	return p
}

func (x MessageToEngineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageToEngineType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_to_engine_proto_enumTypes[0].Descriptor()
}

func (MessageToEngineType) Type() protoreflect.EnumType {
	return &file_message_to_engine_proto_enumTypes[0]
}

func (x MessageToEngineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageToEngineType.Descriptor instead.
func (MessageToEngineType) EnumDescriptor() ([]byte, []int) {
	return file_message_to_engine_proto_rawDescGZIP(), []int{0}
}

type CreateOrderPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market string `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Price  int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Qty    int32  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Side   Side   `protobuf:"varint,4,opt,name=side,proto3,enum=common.Side" json:"side,omitempty"`
	UserId string `protobuf:"bytes,5,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CreateOrderPayload) Reset() {
	*x = CreateOrderPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_to_engine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderPayload) ProtoMessage() {}

func (x *CreateOrderPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_to_engine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderPayload.ProtoReflect.Descriptor instead.
func (*CreateOrderPayload) Descriptor() ([]byte, []int) {
	return file_message_to_engine_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderPayload) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *CreateOrderPayload) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderPayload) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CreateOrderPayload) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_buy
}

func (x *CreateOrderPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelOrderPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Market  string `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
}

func (x *CancelOrderPayload) Reset() {
	*x = CancelOrderPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_to_engine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderPayload) ProtoMessage() {}

func (x *CancelOrderPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_to_engine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderPayload.ProtoReflect.Descriptor instead.
func (*CancelOrderPayload) Descriptor() ([]byte, []int) {
	return file_message_to_engine_proto_rawDescGZIP(), []int{1}
}

func (x *CancelOrderPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderPayload) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

type OnRampPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	TxnId  string `protobuf:"bytes,3,opt,name=txnId,proto3" json:"txnId,omitempty"`
}

func (x *OnRampPayload) Reset() {
	*x = OnRampPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_to_engine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnRampPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnRampPayload) ProtoMessage() {}

func (x *OnRampPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_to_engine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnRampPayload.ProtoReflect.Descriptor instead.
func (*OnRampPayload) Descriptor() ([]byte, []int) {
	return file_message_to_engine_proto_rawDescGZIP(), []int{2}
}

func (x *OnRampPayload) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OnRampPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OnRampPayload) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

type GetDepthPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market string `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
}

func (x *GetDepthPayload) Reset() {
	*x = GetDepthPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_to_engine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepthPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthPayload) ProtoMessage() {}

func (x *GetDepthPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_to_engine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthPayload.ProtoReflect.Descriptor instead.
func (*GetDepthPayload) Descriptor() ([]byte, []int) {
	return file_message_to_engine_proto_rawDescGZIP(), []int{3}
}

func (x *GetDepthPayload) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

type GetOpenOrdersPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Market string `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
}

func (x *GetOpenOrdersPayload) Reset() {
	*x = GetOpenOrdersPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_to_engine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpenOrdersPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenOrdersPayload) ProtoMessage() {}

func (x *GetOpenOrdersPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_to_engine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenOrdersPayload.ProtoReflect.Descriptor instead.
func (*GetOpenOrdersPayload) Descriptor() ([]byte, []int) {
	return file_message_to_engine_proto_rawDescGZIP(), []int{4}
}

func (x *GetOpenOrdersPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOpenOrdersPayload) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

type MessageToEngine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MessageToEngineType `protobuf:"varint,1,opt,name=type,proto3,enum=message_to_engine.MessageToEngineType" json:"type,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*MessageToEngine_CreateOrder
	//	*MessageToEngine_CancelOrder
	//	*MessageToEngine_OnRamp
	//	*MessageToEngine_GetDepth
	//	*MessageToEngine_GetOpenOrders
	Payload isMessageToEngine_Payload `protobuf_oneof:"payload"`
}

func (x *MessageToEngine) Reset() {
	*x = MessageToEngine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_to_engine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageToEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageToEngine) ProtoMessage() {}

func (x *MessageToEngine) ProtoReflect() protoreflect.Message {
	mi := &file_message_to_engine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageToEngine.ProtoReflect.Descriptor instead.
func (*MessageToEngine) Descriptor() ([]byte, []int) {
	return file_message_to_engine_proto_rawDescGZIP(), []int{5}
}

func (x *MessageToEngine) GetType() MessageToEngineType {
	if x != nil {
		return x.Type
	}
	return MessageToEngineType_CREATE_ORDER
}

func (m *MessageToEngine) GetPayload() isMessageToEngine_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *MessageToEngine) GetCreateOrder() *CreateOrderPayload {
	if x, ok := x.GetPayload().(*MessageToEngine_CreateOrder); ok {
		return x.CreateOrder
	}
	return nil
}

func (x *MessageToEngine) GetCancelOrder() *CancelOrderPayload {
	if x, ok := x.GetPayload().(*MessageToEngine_CancelOrder); ok {
		return x.CancelOrder
	}
	return nil
}

func (x *MessageToEngine) GetOnRamp() *OnRampPayload {
	if x, ok := x.GetPayload().(*MessageToEngine_OnRamp); ok {
		return x.OnRamp
	}
	return nil
}

func (x *MessageToEngine) GetGetDepth() *GetDepthPayload {
	if x, ok := x.GetPayload().(*MessageToEngine_GetDepth); ok {
		return x.GetDepth
	}
	return nil
}

func (x *MessageToEngine) GetGetOpenOrders() *GetOpenOrdersPayload {
	if x, ok := x.GetPayload().(*MessageToEngine_GetOpenOrders); ok {
		return x.GetOpenOrders
	}
	return nil
}

type isMessageToEngine_Payload interface {
	isMessageToEngine_Payload()
}

type MessageToEngine_CreateOrder struct {
	CreateOrder *CreateOrderPayload `protobuf:"bytes,2,opt,name=create_order,json=createOrder,proto3,oneof"`
}

type MessageToEngine_CancelOrder struct {
	CancelOrder *CancelOrderPayload `protobuf:"bytes,3,opt,name=cancel_order,json=cancelOrder,proto3,oneof"`
}

type MessageToEngine_OnRamp struct {
	OnRamp *OnRampPayload `protobuf:"bytes,4,opt,name=on_ramp,json=onRamp,proto3,oneof"`
}

type MessageToEngine_GetDepth struct {
	GetDepth *GetDepthPayload `protobuf:"bytes,5,opt,name=get_depth,json=getDepth,proto3,oneof"`
}

type MessageToEngine_GetOpenOrders struct {
	GetOpenOrders *GetOpenOrdersPayload `protobuf:"bytes,6,opt,name=get_open_orders,json=getOpenOrders,proto3,oneof"`
}

func (*MessageToEngine_CreateOrder) isMessageToEngine_Payload() {}

func (*MessageToEngine_CancelOrder) isMessageToEngine_Payload() {}

func (*MessageToEngine_OnRamp) isMessageToEngine_Payload() {}

func (*MessageToEngine_GetDepth) isMessageToEngine_Payload() {}

func (*MessageToEngine_GetOpenOrders) isMessageToEngine_Payload() {}

var File_message_to_engine_proto protoreflect.FileDescriptor

var file_message_to_engine_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74,
	0x79, 0x12, 0x20, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x52, 0x04, 0x73,
	0x69, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x12, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x22, 0x55, 0x0a, 0x0d, 0x4f, 0x6e, 0x52, 0x61, 0x6d, 0x70, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x70, 0x74, 0x68, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x22, 0x46, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x22, 0xc3, 0x03,
	0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x45, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x12, 0x3a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x26, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x45, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x4a, 0x0a,
	0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x0c, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x07, 0x6f, 0x6e, 0x5f, 0x72, 0x61, 0x6d, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x74, 0x6f, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x4f, 0x6e, 0x52, 0x61, 0x6d,
	0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x6e, 0x52, 0x61,
	0x6d, 0x70, 0x12, 0x41, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x5f, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x6f, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70,
	0x74, 0x68, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x08, 0x67, 0x65, 0x74,
	0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x51, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x5f, 0x6f, 0x70, 0x65,
	0x6e, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x65, 0x74, 0x4f, 0x70,
	0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2a, 0x6a, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x4f, 0x4e, 0x5f, 0x52, 0x41, 0x4d, 0x50, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x47,
	0x45, 0x54, 0x5f, 0x44, 0x45, 0x50, 0x54, 0x48, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x45,
	0x54, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x53, 0x10, 0x04, 0x42,
	0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61,
	0x67, 0x68, 0x61, 0x76, 0x31, 0x30, 0x33, 0x30, 0x2f, 0x6b, 0x61, 0x7a, 0x65, 0x78, 0x2f, 0x63,
	0x6d, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_to_engine_proto_rawDescOnce sync.Once
	file_message_to_engine_proto_rawDescData = file_message_to_engine_proto_rawDesc
)

func file_message_to_engine_proto_rawDescGZIP() []byte {
	file_message_to_engine_proto_rawDescOnce.Do(func() {
		file_message_to_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_to_engine_proto_rawDescData)
	})
	return file_message_to_engine_proto_rawDescData
}

var file_message_to_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_to_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_message_to_engine_proto_goTypes = []any{
	(MessageToEngineType)(0),     // 0: message_to_engine.MessageToEngineType
	(*CreateOrderPayload)(nil),   // 1: message_to_engine.CreateOrderPayload
	(*CancelOrderPayload)(nil),   // 2: message_to_engine.CancelOrderPayload
	(*OnRampPayload)(nil),        // 3: message_to_engine.OnRampPayload
	(*GetDepthPayload)(nil),      // 4: message_to_engine.GetDepthPayload
	(*GetOpenOrdersPayload)(nil), // 5: message_to_engine.GetOpenOrdersPayload
	(*MessageToEngine)(nil),      // 6: message_to_engine.MessageToEngine
	(Side)(0),                    // 7: common.Side
}
var file_message_to_engine_proto_depIdxs = []int32{
	7, // 0: message_to_engine.CreateOrderPayload.side:type_name -> common.Side
	0, // 1: message_to_engine.MessageToEngine.type:type_name -> message_to_engine.MessageToEngineType
	1, // 2: message_to_engine.MessageToEngine.create_order:type_name -> message_to_engine.CreateOrderPayload
	2, // 3: message_to_engine.MessageToEngine.cancel_order:type_name -> message_to_engine.CancelOrderPayload
	3, // 4: message_to_engine.MessageToEngine.on_ramp:type_name -> message_to_engine.OnRampPayload
	4, // 5: message_to_engine.MessageToEngine.get_depth:type_name -> message_to_engine.GetDepthPayload
	5, // 6: message_to_engine.MessageToEngine.get_open_orders:type_name -> message_to_engine.GetOpenOrdersPayload
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_message_to_engine_proto_init() }
func file_message_to_engine_proto_init() {
	if File_message_to_engine_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_to_engine_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateOrderPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_to_engine_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CancelOrderPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_to_engine_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OnRampPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_to_engine_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetDepthPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_to_engine_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetOpenOrdersPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_to_engine_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*MessageToEngine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_to_engine_proto_msgTypes[5].OneofWrappers = []any{
		(*MessageToEngine_CreateOrder)(nil),
		(*MessageToEngine_CancelOrder)(nil),
		(*MessageToEngine_OnRamp)(nil),
		(*MessageToEngine_GetDepth)(nil),
		(*MessageToEngine_GetOpenOrders)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_to_engine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_to_engine_proto_goTypes,
		DependencyIndexes: file_message_to_engine_proto_depIdxs,
		EnumInfos:         file_message_to_engine_proto_enumTypes,
		MessageInfos:      file_message_to_engine_proto_msgTypes,
	}.Build()
	File_message_to_engine_proto = out.File
	file_message_to_engine_proto_rawDesc = nil
	file_message_to_engine_proto_goTypes = nil
	file_message_to_engine_proto_depIdxs = nil
}
