// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: message_from_orderbook.proto

package protobuf_generated_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidAsk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price    string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity string `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *BidAsk) Reset() {
	*x = BidAsk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAsk) ProtoMessage() {}

func (x *BidAsk) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAsk.ProtoReflect.Descriptor instead.
func (*BidAsk) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *BidAsk) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *BidAsk) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type DepthPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market string    `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Bids   []*BidAsk `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks   []*BidAsk `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
}

func (x *DepthPayload) Reset() {
	*x = DepthPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepthPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthPayload) ProtoMessage() {}

func (x *DepthPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthPayload.ProtoReflect.Descriptor instead.
func (*DepthPayload) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *DepthPayload) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *DepthPayload) GetBids() []*BidAsk {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *DepthPayload) GetAsks() []*BidAsk {
	if x != nil {
		return x.Asks
	}
	return nil
}

type OpenOrdersPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	ExecutedQty int32  `protobuf:"varint,2,opt,name=executedQty,proto3" json:"executedQty,omitempty"`
	Price       string `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Qty         string `protobuf:"bytes,4,opt,name=qty,proto3" json:"qty,omitempty"`
	Side        Side   `protobuf:"varint,5,opt,name=side,proto3,enum=common.Side" json:"side,omitempty"`
	UserId      string `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *OpenOrdersPayload) Reset() {
	*x = OpenOrdersPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenOrdersPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrdersPayload) ProtoMessage() {}

func (x *OpenOrdersPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrdersPayload.ProtoReflect.Descriptor instead.
func (*OpenOrdersPayload) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *OpenOrdersPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OpenOrdersPayload) GetExecutedQty() int32 {
	if x != nil {
		return x.ExecutedQty
	}
	return 0
}

func (x *OpenOrdersPayload) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OpenOrdersPayload) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *OpenOrdersPayload) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_buy
}

func (x *OpenOrdersPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type OrderPlacedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	ExecutedQty int32    `protobuf:"varint,2,opt,name=executedQty,proto3" json:"executedQty,omitempty"`
	Fills       []*Fills `protobuf:"bytes,3,rep,name=fills,proto3" json:"fills,omitempty"`
}

func (x *OrderPlacedPayload) Reset() {
	*x = OrderPlacedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPlacedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPlacedPayload) ProtoMessage() {}

func (x *OrderPlacedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPlacedPayload.ProtoReflect.Descriptor instead.
func (*OrderPlacedPayload) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *OrderPlacedPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderPlacedPayload) GetExecutedQty() int32 {
	if x != nil {
		return x.ExecutedQty
	}
	return 0
}

func (x *OrderPlacedPayload) GetFills() []*Fills {
	if x != nil {
		return x.Fills
	}
	return nil
}

type Fills struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price   string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Qty     int32  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	TradeId int32  `protobuf:"varint,3,opt,name=tradeId,proto3" json:"tradeId,omitempty"`
}

func (x *Fills) Reset() {
	*x = Fills{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fills) ProtoMessage() {}

func (x *Fills) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fills.ProtoReflect.Descriptor instead.
func (*Fills) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *Fills) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Fills) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Fills) GetTradeId() int32 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

type OrderCancelledPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId      string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	ExecutedQty  int32  `protobuf:"varint,2,opt,name=executedQty,proto3" json:"executedQty,omitempty"`
	RemainingQty int32  `protobuf:"varint,3,opt,name=remainingQty,proto3" json:"remainingQty,omitempty"`
}

func (x *OrderCancelledPayload) Reset() {
	*x = OrderCancelledPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCancelledPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelledPayload) ProtoMessage() {}

func (x *OrderCancelledPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelledPayload.ProtoReflect.Descriptor instead.
func (*OrderCancelledPayload) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *OrderCancelledPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCancelledPayload) GetExecutedQty() int32 {
	if x != nil {
		return x.ExecutedQty
	}
	return 0
}

func (x *OrderCancelledPayload) GetRemainingQty() int32 {
	if x != nil {
		return x.RemainingQty
	}
	return 0
}

type DepthMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload *DepthPayload `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *DepthMessage) Reset() {
	*x = DepthMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthMessage) ProtoMessage() {}

func (x *DepthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthMessage.ProtoReflect.Descriptor instead.
func (*DepthMessage) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{6}
}

func (x *DepthMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DepthMessage) GetPayload() *DepthPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OpenOrdersMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string             `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload *OpenOrdersPayload `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *OpenOrdersMessage) Reset() {
	*x = OpenOrdersMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenOrdersMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrdersMessage) ProtoMessage() {}

func (x *OpenOrdersMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrdersMessage.ProtoReflect.Descriptor instead.
func (*OpenOrdersMessage) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{7}
}

func (x *OpenOrdersMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OpenOrdersMessage) GetPayload() *OpenOrdersPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OrderCompletedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string              `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload *OrderPlacedPayload `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *OrderCompletedMessage) Reset() {
	*x = OrderCompletedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCompletedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCompletedMessage) ProtoMessage() {}

func (x *OrderCompletedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCompletedMessage.ProtoReflect.Descriptor instead.
func (*OrderCompletedMessage) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{8}
}

func (x *OrderCompletedMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderCompletedMessage) GetPayload() *OrderPlacedPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OrderCancelledMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload *OrderCancelledPayload `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *OrderCancelledMessage) Reset() {
	*x = OrderCancelledMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCancelledMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelledMessage) ProtoMessage() {}

func (x *OrderCancelledMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelledMessage.ProtoReflect.Descriptor instead.
func (*OrderCancelledMessage) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{9}
}

func (x *OrderCancelledMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderCancelledMessage) GetPayload() *OrderCancelledPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MessageFromOrderBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*MessageFromOrderBook_DepthMessage
	//	*MessageFromOrderBook_OpenOrdersMessage
	//	*MessageFromOrderBook_OrderCompletedMessage
	//	*MessageFromOrderBook_OrderCancelledMessage
	Payload isMessageFromOrderBook_Payload `protobuf_oneof:"payload"`
}

func (x *MessageFromOrderBook) Reset() {
	*x = MessageFromOrderBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFromOrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFromOrderBook) ProtoMessage() {}

func (x *MessageFromOrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFromOrderBook.ProtoReflect.Descriptor instead.
func (*MessageFromOrderBook) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{10}
}

func (m *MessageFromOrderBook) GetPayload() isMessageFromOrderBook_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *MessageFromOrderBook) GetDepthMessage() *DepthMessage {
	if x, ok := x.GetPayload().(*MessageFromOrderBook_DepthMessage); ok {
		return x.DepthMessage
	}
	return nil
}

func (x *MessageFromOrderBook) GetOpenOrdersMessage() *OpenOrdersMessage {
	if x, ok := x.GetPayload().(*MessageFromOrderBook_OpenOrdersMessage); ok {
		return x.OpenOrdersMessage
	}
	return nil
}

func (x *MessageFromOrderBook) GetOrderCompletedMessage() *OrderCompletedMessage {
	if x, ok := x.GetPayload().(*MessageFromOrderBook_OrderCompletedMessage); ok {
		return x.OrderCompletedMessage
	}
	return nil
}

func (x *MessageFromOrderBook) GetOrderCancelledMessage() *OrderCancelledMessage {
	if x, ok := x.GetPayload().(*MessageFromOrderBook_OrderCancelledMessage); ok {
		return x.OrderCancelledMessage
	}
	return nil
}

type isMessageFromOrderBook_Payload interface {
	isMessageFromOrderBook_Payload()
}

type MessageFromOrderBook_DepthMessage struct {
	DepthMessage *DepthMessage `protobuf:"bytes,2,opt,name=depth_message,json=depthMessage,proto3,oneof"`
}

type MessageFromOrderBook_OpenOrdersMessage struct {
	OpenOrdersMessage *OpenOrdersMessage `protobuf:"bytes,3,opt,name=open_orders_message,json=openOrdersMessage,proto3,oneof"`
}

type MessageFromOrderBook_OrderCompletedMessage struct {
	OrderCompletedMessage *OrderCompletedMessage `protobuf:"bytes,4,opt,name=order_completed_message,json=orderCompletedMessage,proto3,oneof"`
}

type MessageFromOrderBook_OrderCancelledMessage struct {
	OrderCancelledMessage *OrderCancelledMessage `protobuf:"bytes,5,opt,name=order_cancelled_message,json=orderCancelledMessage,proto3,oneof"`
}

func (*MessageFromOrderBook_DepthMessage) isMessageFromOrderBook_Payload() {}

func (*MessageFromOrderBook_OpenOrdersMessage) isMessageFromOrderBook_Payload() {}

func (*MessageFromOrderBook_OrderCompletedMessage) isMessageFromOrderBook_Payload() {}

func (*MessageFromOrderBook_OrderCancelledMessage) isMessageFromOrderBook_Payload() {}

var File_message_from_orderbook_proto protoreflect.FileDescriptor

var file_message_from_orderbook_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x06, 0x42, 0x69, 0x64, 0x41, 0x73,
	0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x74, 0x68, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x35, 0x0a, 0x04,
	0x62, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x42, 0x69, 0x64, 0x41, 0x73, 0x6b, 0x52, 0x04, 0x62,
	0x69, 0x64, 0x73, 0x12, 0x35, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x42, 0x69,
	0x64, 0x41, 0x73, 0x6b, 0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x11, 0x4f,
	0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x71, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x64, 0x65,
	0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x88,
	0x01, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x64, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74,
	0x79, 0x12, 0x36, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x6c,
	0x6c, 0x73, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x6c, 0x73, 0x22, 0x49, 0x0a, 0x05, 0x46, 0x69, 0x6c,
	0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x64, 0x65, 0x49, 0x64, 0x22, 0x77, 0x0a, 0x15, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x51, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x51, 0x74, 0x79, 0x22, 0x65, 0x0a,
	0x0c, 0x44, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x41, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x44,
	0x65, 0x70, 0x74, 0x68, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x6f, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x46, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x74, 0x0a, 0x15, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x47, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x77, 0x0a, 0x15, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x4a, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x6c, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0xa9, 0x03, 0x0a, 0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x4e, 0x0a,
	0x0d, 0x64, 0x65, 0x70, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x0c, 0x64, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x5e, 0x0a,
	0x13, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x11, 0x6f, 0x70, 0x65, 0x6e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x6a, 0x0a,
	0x17, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x15, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x6a, 0x0a, 0x17, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x6c, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x15,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x42, 0x1c, 0x5a, 0x1a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_from_orderbook_proto_rawDescOnce sync.Once
	file_message_from_orderbook_proto_rawDescData = file_message_from_orderbook_proto_rawDesc
)

func file_message_from_orderbook_proto_rawDescGZIP() []byte {
	file_message_from_orderbook_proto_rawDescOnce.Do(func() {
		file_message_from_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_from_orderbook_proto_rawDescData)
	})
	return file_message_from_orderbook_proto_rawDescData
}

var file_message_from_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_message_from_orderbook_proto_goTypes = []any{
	(*BidAsk)(nil),                // 0: orderbook_engine_messages.BidAsk
	(*DepthPayload)(nil),          // 1: orderbook_engine_messages.DepthPayload
	(*OpenOrdersPayload)(nil),     // 2: orderbook_engine_messages.OpenOrdersPayload
	(*OrderPlacedPayload)(nil),    // 3: orderbook_engine_messages.OrderPlacedPayload
	(*Fills)(nil),                 // 4: orderbook_engine_messages.Fills
	(*OrderCancelledPayload)(nil), // 5: orderbook_engine_messages.OrderCancelledPayload
	(*DepthMessage)(nil),          // 6: orderbook_engine_messages.DepthMessage
	(*OpenOrdersMessage)(nil),     // 7: orderbook_engine_messages.OpenOrdersMessage
	(*OrderCompletedMessage)(nil), // 8: orderbook_engine_messages.OrderCompletedMessage
	(*OrderCancelledMessage)(nil), // 9: orderbook_engine_messages.OrderCancelledMessage
	(*MessageFromOrderBook)(nil),  // 10: orderbook_engine_messages.MessageFromOrderBook
	(Side)(0),                     // 11: common.Side
}
var file_message_from_orderbook_proto_depIdxs = []int32{
	0,  // 0: orderbook_engine_messages.DepthPayload.bids:type_name -> orderbook_engine_messages.BidAsk
	0,  // 1: orderbook_engine_messages.DepthPayload.asks:type_name -> orderbook_engine_messages.BidAsk
	11, // 2: orderbook_engine_messages.OpenOrdersPayload.side:type_name -> common.Side
	4,  // 3: orderbook_engine_messages.OrderPlacedPayload.fills:type_name -> orderbook_engine_messages.Fills
	1,  // 4: orderbook_engine_messages.DepthMessage.payload:type_name -> orderbook_engine_messages.DepthPayload
	2,  // 5: orderbook_engine_messages.OpenOrdersMessage.payload:type_name -> orderbook_engine_messages.OpenOrdersPayload
	3,  // 6: orderbook_engine_messages.OrderCompletedMessage.payload:type_name -> orderbook_engine_messages.OrderPlacedPayload
	5,  // 7: orderbook_engine_messages.OrderCancelledMessage.payload:type_name -> orderbook_engine_messages.OrderCancelledPayload
	6,  // 8: orderbook_engine_messages.MessageFromOrderBook.depth_message:type_name -> orderbook_engine_messages.DepthMessage
	7,  // 9: orderbook_engine_messages.MessageFromOrderBook.open_orders_message:type_name -> orderbook_engine_messages.OpenOrdersMessage
	8,  // 10: orderbook_engine_messages.MessageFromOrderBook.order_completed_message:type_name -> orderbook_engine_messages.OrderCompletedMessage
	9,  // 11: orderbook_engine_messages.MessageFromOrderBook.order_cancelled_message:type_name -> orderbook_engine_messages.OrderCancelledMessage
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_message_from_orderbook_proto_init() }
func file_message_from_orderbook_proto_init() {
	if File_message_from_orderbook_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_from_orderbook_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BidAsk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DepthPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OpenOrdersPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*OrderPlacedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Fills); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*OrderCancelledPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DepthMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*OpenOrdersMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*OrderCompletedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*OrderCancelledMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*MessageFromOrderBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_from_orderbook_proto_msgTypes[10].OneofWrappers = []any{
		(*MessageFromOrderBook_DepthMessage)(nil),
		(*MessageFromOrderBook_OpenOrdersMessage)(nil),
		(*MessageFromOrderBook_OrderCompletedMessage)(nil),
		(*MessageFromOrderBook_OrderCancelledMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_from_orderbook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_from_orderbook_proto_goTypes,
		DependencyIndexes: file_message_from_orderbook_proto_depIdxs,
		MessageInfos:      file_message_from_orderbook_proto_msgTypes,
	}.Build()
	File_message_from_orderbook_proto = out.File
	file_message_from_orderbook_proto_rawDesc = nil
	file_message_from_orderbook_proto_goTypes = nil
	file_message_from_orderbook_proto_depIdxs = nil
}
