// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: message_from_orderbook.proto

package protobuf_generated_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageFromOrderbookType int32

const (
	MessageFromOrderbookType_DEPTH           MessageFromOrderbookType = 0
	MessageFromOrderbookType_ORDER_PLACED    MessageFromOrderbookType = 1
	MessageFromOrderbookType_ORDER_CANCELLED MessageFromOrderbookType = 2
	MessageFromOrderbookType_OPEN_ORDERS     MessageFromOrderbookType = 3
)

// Enum value maps for MessageFromOrderbookType.
var (
	MessageFromOrderbookType_name = map[int32]string{
		0: "DEPTH",
		1: "ORDER_PLACED",
		2: "ORDER_CANCELLED",
		3: "OPEN_ORDERS",
	}
	MessageFromOrderbookType_value = map[string]int32{
		"DEPTH":           0,
		"ORDER_PLACED":    1,
		"ORDER_CANCELLED": 2,
		"OPEN_ORDERS":     3,
	}
)

func (x MessageFromOrderbookType) Enum() *MessageFromOrderbookType {
	p := new(MessageFromOrderbookType)
	*p = x
	return p
}

func (x MessageFromOrderbookType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageFromOrderbookType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_from_orderbook_proto_enumTypes[0].Descriptor()
}

func (MessageFromOrderbookType) Type() protoreflect.EnumType {
	return &file_message_from_orderbook_proto_enumTypes[0]
}

func (x MessageFromOrderbookType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageFromOrderbookType.Descriptor instead.
func (MessageFromOrderbookType) EnumDescriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{0}
}

type BidAsk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price    string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity string `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *BidAsk) Reset() {
	*x = BidAsk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidAsk) ProtoMessage() {}

func (x *BidAsk) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidAsk.ProtoReflect.Descriptor instead.
func (*BidAsk) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *BidAsk) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *BidAsk) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type DepthPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market string    `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Bids   []*BidAsk `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks   []*BidAsk `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
}

func (x *DepthPayload) Reset() {
	*x = DepthPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepthPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthPayload) ProtoMessage() {}

func (x *DepthPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthPayload.ProtoReflect.Descriptor instead.
func (*DepthPayload) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *DepthPayload) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *DepthPayload) GetBids() []*BidAsk {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *DepthPayload) GetAsks() []*BidAsk {
	if x != nil {
		return x.Asks
	}
	return nil
}

type OpenOrdersPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	ExecutedQty int32  `protobuf:"varint,2,opt,name=executedQty,proto3" json:"executedQty,omitempty"`
	Price       string `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Qty         string `protobuf:"bytes,4,opt,name=qty,proto3" json:"qty,omitempty"`
	Side        Side   `protobuf:"varint,5,opt,name=side,proto3,enum=common.Side" json:"side,omitempty"`
	UserId      string `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *OpenOrdersPayload) Reset() {
	*x = OpenOrdersPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenOrdersPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrdersPayload) ProtoMessage() {}

func (x *OpenOrdersPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrdersPayload.ProtoReflect.Descriptor instead.
func (*OpenOrdersPayload) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *OpenOrdersPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OpenOrdersPayload) GetExecutedQty() int32 {
	if x != nil {
		return x.ExecutedQty
	}
	return 0
}

func (x *OpenOrdersPayload) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OpenOrdersPayload) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *OpenOrdersPayload) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_buy
}

func (x *OpenOrdersPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type OrderCompletedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	ExecutedQty int32    `protobuf:"varint,2,opt,name=executedQty,proto3" json:"executedQty,omitempty"`
	Fills       []*Fills `protobuf:"bytes,3,rep,name=fills,proto3" json:"fills,omitempty"`
}

func (x *OrderCompletedPayload) Reset() {
	*x = OrderCompletedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCompletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCompletedPayload) ProtoMessage() {}

func (x *OrderCompletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCompletedPayload.ProtoReflect.Descriptor instead.
func (*OrderCompletedPayload) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCompletedPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCompletedPayload) GetExecutedQty() int32 {
	if x != nil {
		return x.ExecutedQty
	}
	return 0
}

func (x *OrderCompletedPayload) GetFills() []*Fills {
	if x != nil {
		return x.Fills
	}
	return nil
}

type Fills struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price   string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Qty     int32  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	TradeId int32  `protobuf:"varint,3,opt,name=tradeId,proto3" json:"tradeId,omitempty"`
}

func (x *Fills) Reset() {
	*x = Fills{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fills) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fills) ProtoMessage() {}

func (x *Fills) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fills.ProtoReflect.Descriptor instead.
func (*Fills) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{4}
}

func (x *Fills) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Fills) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Fills) GetTradeId() int32 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

type OrderCancelledPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId      string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	ExecutedQty  int32  `protobuf:"varint,2,opt,name=executedQty,proto3" json:"executedQty,omitempty"`
	RemainingQty int32  `protobuf:"varint,3,opt,name=remainingQty,proto3" json:"remainingQty,omitempty"`
}

func (x *OrderCancelledPayload) Reset() {
	*x = OrderCancelledPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCancelledPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelledPayload) ProtoMessage() {}

func (x *OrderCancelledPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelledPayload.ProtoReflect.Descriptor instead.
func (*OrderCancelledPayload) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{5}
}

func (x *OrderCancelledPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCancelledPayload) GetExecutedQty() int32 {
	if x != nil {
		return x.ExecutedQty
	}
	return 0
}

func (x *OrderCancelledPayload) GetRemainingQty() int32 {
	if x != nil {
		return x.RemainingQty
	}
	return 0
}

type DepthMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         MessageFromOrderbookType `protobuf:"varint,1,opt,name=type,proto3,enum=orderbook_engine_messages.MessageFromOrderbookType" json:"type,omitempty"`
	DepthPayload *DepthPayload            `protobuf:"bytes,2,opt,name=depth_payload,json=depthPayload,proto3" json:"depth_payload,omitempty"`
}

func (x *DepthMessage) Reset() {
	*x = DepthMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthMessage) ProtoMessage() {}

func (x *DepthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthMessage.ProtoReflect.Descriptor instead.
func (*DepthMessage) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{6}
}

func (x *DepthMessage) GetType() MessageFromOrderbookType {
	if x != nil {
		return x.Type
	}
	return MessageFromOrderbookType_DEPTH
}

func (x *DepthMessage) GetDepthPayload() *DepthPayload {
	if x != nil {
		return x.DepthPayload
	}
	return nil
}

type OpenOrdersMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type              MessageFromOrderbookType `protobuf:"varint,1,opt,name=type,proto3,enum=orderbook_engine_messages.MessageFromOrderbookType" json:"type,omitempty"`
	OpenOrdersPayload *OpenOrdersPayload       `protobuf:"bytes,2,opt,name=open_orders_payload,json=openOrdersPayload,proto3" json:"open_orders_payload,omitempty"`
}

func (x *OpenOrdersMessage) Reset() {
	*x = OpenOrdersMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenOrdersMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenOrdersMessage) ProtoMessage() {}

func (x *OpenOrdersMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenOrdersMessage.ProtoReflect.Descriptor instead.
func (*OpenOrdersMessage) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{7}
}

func (x *OpenOrdersMessage) GetType() MessageFromOrderbookType {
	if x != nil {
		return x.Type
	}
	return MessageFromOrderbookType_DEPTH
}

func (x *OpenOrdersMessage) GetOpenOrdersPayload() *OpenOrdersPayload {
	if x != nil {
		return x.OpenOrdersPayload
	}
	return nil
}

type OrderCompletedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type                  MessageFromOrderbookType `protobuf:"varint,1,opt,name=type,proto3,enum=orderbook_engine_messages.MessageFromOrderbookType" json:"type,omitempty"`
	OrderCompletedPayload *OrderCompletedPayload   `protobuf:"bytes,2,opt,name=order_completed_payload,json=orderCompletedPayload,proto3" json:"order_completed_payload,omitempty"`
}

func (x *OrderCompletedMessage) Reset() {
	*x = OrderCompletedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCompletedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCompletedMessage) ProtoMessage() {}

func (x *OrderCompletedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCompletedMessage.ProtoReflect.Descriptor instead.
func (*OrderCompletedMessage) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{8}
}

func (x *OrderCompletedMessage) GetType() MessageFromOrderbookType {
	if x != nil {
		return x.Type
	}
	return MessageFromOrderbookType_DEPTH
}

func (x *OrderCompletedMessage) GetOrderCompletedPayload() *OrderCompletedPayload {
	if x != nil {
		return x.OrderCompletedPayload
	}
	return nil
}

type OrderCancelledMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type                  MessageFromOrderbookType `protobuf:"varint,1,opt,name=type,proto3,enum=orderbook_engine_messages.MessageFromOrderbookType" json:"type,omitempty"`
	OrderCancelledPayload *OrderCancelledPayload   `protobuf:"bytes,2,opt,name=order_cancelled_payload,json=orderCancelledPayload,proto3" json:"order_cancelled_payload,omitempty"`
}

func (x *OrderCancelledMessage) Reset() {
	*x = OrderCancelledMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCancelledMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelledMessage) ProtoMessage() {}

func (x *OrderCancelledMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelledMessage.ProtoReflect.Descriptor instead.
func (*OrderCancelledMessage) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{9}
}

func (x *OrderCancelledMessage) GetType() MessageFromOrderbookType {
	if x != nil {
		return x.Type
	}
	return MessageFromOrderbookType_DEPTH
}

func (x *OrderCancelledMessage) GetOrderCancelledPayload() *OrderCancelledPayload {
	if x != nil {
		return x.OrderCancelledPayload
	}
	return nil
}

type MessageFromOrderBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MessageFromOrderbookType `protobuf:"varint,1,opt,name=type,proto3,enum=orderbook_engine_messages.MessageFromOrderbookType" json:"type,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*MessageFromOrderBook_DepthPayload
	//	*MessageFromOrderBook_OpenOrdersPayload
	//	*MessageFromOrderBook_OrderCompletedPayload
	//	*MessageFromOrderBook_OrderCancelledPayload
	Payload isMessageFromOrderBook_Payload `protobuf_oneof:"payload"`
}

func (x *MessageFromOrderBook) Reset() {
	*x = MessageFromOrderBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_from_orderbook_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageFromOrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFromOrderBook) ProtoMessage() {}

func (x *MessageFromOrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_message_from_orderbook_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFromOrderBook.ProtoReflect.Descriptor instead.
func (*MessageFromOrderBook) Descriptor() ([]byte, []int) {
	return file_message_from_orderbook_proto_rawDescGZIP(), []int{10}
}

func (x *MessageFromOrderBook) GetType() MessageFromOrderbookType {
	if x != nil {
		return x.Type
	}
	return MessageFromOrderbookType_DEPTH
}

func (m *MessageFromOrderBook) GetPayload() isMessageFromOrderBook_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *MessageFromOrderBook) GetDepthPayload() *DepthPayload {
	if x, ok := x.GetPayload().(*MessageFromOrderBook_DepthPayload); ok {
		return x.DepthPayload
	}
	return nil
}

func (x *MessageFromOrderBook) GetOpenOrdersPayload() *OpenOrdersPayload {
	if x, ok := x.GetPayload().(*MessageFromOrderBook_OpenOrdersPayload); ok {
		return x.OpenOrdersPayload
	}
	return nil
}

func (x *MessageFromOrderBook) GetOrderCompletedPayload() *OrderCompletedPayload {
	if x, ok := x.GetPayload().(*MessageFromOrderBook_OrderCompletedPayload); ok {
		return x.OrderCompletedPayload
	}
	return nil
}

func (x *MessageFromOrderBook) GetOrderCancelledPayload() *OrderCancelledPayload {
	if x, ok := x.GetPayload().(*MessageFromOrderBook_OrderCancelledPayload); ok {
		return x.OrderCancelledPayload
	}
	return nil
}

type isMessageFromOrderBook_Payload interface {
	isMessageFromOrderBook_Payload()
}

type MessageFromOrderBook_DepthPayload struct {
	DepthPayload *DepthPayload `protobuf:"bytes,2,opt,name=depth_payload,json=depthPayload,proto3,oneof"`
}

type MessageFromOrderBook_OpenOrdersPayload struct {
	OpenOrdersPayload *OpenOrdersPayload `protobuf:"bytes,3,opt,name=open_orders_payload,json=openOrdersPayload,proto3,oneof"`
}

type MessageFromOrderBook_OrderCompletedPayload struct {
	OrderCompletedPayload *OrderCompletedPayload `protobuf:"bytes,4,opt,name=order_completed_payload,json=orderCompletedPayload,proto3,oneof"`
}

type MessageFromOrderBook_OrderCancelledPayload struct {
	OrderCancelledPayload *OrderCancelledPayload `protobuf:"bytes,5,opt,name=order_cancelled_payload,json=orderCancelledPayload,proto3,oneof"`
}

func (*MessageFromOrderBook_DepthPayload) isMessageFromOrderBook_Payload() {}

func (*MessageFromOrderBook_OpenOrdersPayload) isMessageFromOrderBook_Payload() {}

func (*MessageFromOrderBook_OrderCompletedPayload) isMessageFromOrderBook_Payload() {}

func (*MessageFromOrderBook_OrderCancelledPayload) isMessageFromOrderBook_Payload() {}

var File_message_from_orderbook_proto protoreflect.FileDescriptor

var file_message_from_orderbook_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x06, 0x42, 0x69, 0x64, 0x41, 0x73,
	0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x74, 0x68, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x35, 0x0a, 0x04,
	0x62, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x42, 0x69, 0x64, 0x41, 0x73, 0x6b, 0x52, 0x04, 0x62,
	0x69, 0x64, 0x73, 0x12, 0x35, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x42, 0x69,
	0x64, 0x41, 0x73, 0x6b, 0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x11, 0x4f,
	0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x71, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x64, 0x65,
	0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8b,
	0x01, 0x0a, 0x15, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x64, 0x51, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x46, 0x69, 0x6c, 0x6c, 0x73, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x6c, 0x73, 0x22, 0x49, 0x0a, 0x05,
	0x46, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x49, 0x64, 0x22, 0x77, 0x0a, 0x15, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0c,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x51, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x51, 0x74, 0x79,
	0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x44, 0x65, 0x70, 0x74, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x47, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x33, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x64, 0x65,
	0x70, 0x74, 0x68, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x44, 0x65,
	0x70, 0x74, 0x68, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x74,
	0x68, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xba, 0x01, 0x0a, 0x11, 0x4f, 0x70, 0x65,
	0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x47,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x5c, 0x0a, 0x13, 0x6f, 0x70, 0x65, 0x6e, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b,
	0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x11, 0x6f, 0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xca, 0x01, 0x0a, 0x15, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x47, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x68, 0x0a, 0x17, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x15, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0xca, 0x01, 0x0a, 0x15, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x6c, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x47, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x68, 0x0a, 0x17, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65,
	0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x15, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0xf2, 0x03, 0x0a, 0x14, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x47, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x74, 0x68, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x68, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x74, 0x68, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x5e, 0x0a, 0x13, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x11,
	0x6f, 0x70, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x6a, 0x0a, 0x17, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x15, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x6a, 0x0a,
	0x17, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64,
	0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x48, 0x00, 0x52, 0x15, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c,
	0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x5d, 0x0a, 0x18, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x50, 0x54, 0x48, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x44, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x50, 0x45, 0x4e, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52,
	0x53, 0x10, 0x03, 0x42, 0x1c, 0x5a, 0x1a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_from_orderbook_proto_rawDescOnce sync.Once
	file_message_from_orderbook_proto_rawDescData = file_message_from_orderbook_proto_rawDesc
)

func file_message_from_orderbook_proto_rawDescGZIP() []byte {
	file_message_from_orderbook_proto_rawDescOnce.Do(func() {
		file_message_from_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_from_orderbook_proto_rawDescData)
	})
	return file_message_from_orderbook_proto_rawDescData
}

var file_message_from_orderbook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_from_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_message_from_orderbook_proto_goTypes = []any{
	(MessageFromOrderbookType)(0), // 0: orderbook_engine_messages.MessageFromOrderbookType
	(*BidAsk)(nil),                // 1: orderbook_engine_messages.BidAsk
	(*DepthPayload)(nil),          // 2: orderbook_engine_messages.DepthPayload
	(*OpenOrdersPayload)(nil),     // 3: orderbook_engine_messages.OpenOrdersPayload
	(*OrderCompletedPayload)(nil), // 4: orderbook_engine_messages.OrderCompletedPayload
	(*Fills)(nil),                 // 5: orderbook_engine_messages.Fills
	(*OrderCancelledPayload)(nil), // 6: orderbook_engine_messages.OrderCancelledPayload
	(*DepthMessage)(nil),          // 7: orderbook_engine_messages.DepthMessage
	(*OpenOrdersMessage)(nil),     // 8: orderbook_engine_messages.OpenOrdersMessage
	(*OrderCompletedMessage)(nil), // 9: orderbook_engine_messages.OrderCompletedMessage
	(*OrderCancelledMessage)(nil), // 10: orderbook_engine_messages.OrderCancelledMessage
	(*MessageFromOrderBook)(nil),  // 11: orderbook_engine_messages.MessageFromOrderBook
	(Side)(0),                     // 12: common.Side
}
var file_message_from_orderbook_proto_depIdxs = []int32{
	1,  // 0: orderbook_engine_messages.DepthPayload.bids:type_name -> orderbook_engine_messages.BidAsk
	1,  // 1: orderbook_engine_messages.DepthPayload.asks:type_name -> orderbook_engine_messages.BidAsk
	12, // 2: orderbook_engine_messages.OpenOrdersPayload.side:type_name -> common.Side
	5,  // 3: orderbook_engine_messages.OrderCompletedPayload.fills:type_name -> orderbook_engine_messages.Fills
	0,  // 4: orderbook_engine_messages.DepthMessage.type:type_name -> orderbook_engine_messages.MessageFromOrderbookType
	2,  // 5: orderbook_engine_messages.DepthMessage.depth_payload:type_name -> orderbook_engine_messages.DepthPayload
	0,  // 6: orderbook_engine_messages.OpenOrdersMessage.type:type_name -> orderbook_engine_messages.MessageFromOrderbookType
	3,  // 7: orderbook_engine_messages.OpenOrdersMessage.open_orders_payload:type_name -> orderbook_engine_messages.OpenOrdersPayload
	0,  // 8: orderbook_engine_messages.OrderCompletedMessage.type:type_name -> orderbook_engine_messages.MessageFromOrderbookType
	4,  // 9: orderbook_engine_messages.OrderCompletedMessage.order_completed_payload:type_name -> orderbook_engine_messages.OrderCompletedPayload
	0,  // 10: orderbook_engine_messages.OrderCancelledMessage.type:type_name -> orderbook_engine_messages.MessageFromOrderbookType
	6,  // 11: orderbook_engine_messages.OrderCancelledMessage.order_cancelled_payload:type_name -> orderbook_engine_messages.OrderCancelledPayload
	0,  // 12: orderbook_engine_messages.MessageFromOrderBook.type:type_name -> orderbook_engine_messages.MessageFromOrderbookType
	2,  // 13: orderbook_engine_messages.MessageFromOrderBook.depth_payload:type_name -> orderbook_engine_messages.DepthPayload
	3,  // 14: orderbook_engine_messages.MessageFromOrderBook.open_orders_payload:type_name -> orderbook_engine_messages.OpenOrdersPayload
	4,  // 15: orderbook_engine_messages.MessageFromOrderBook.order_completed_payload:type_name -> orderbook_engine_messages.OrderCompletedPayload
	6,  // 16: orderbook_engine_messages.MessageFromOrderBook.order_cancelled_payload:type_name -> orderbook_engine_messages.OrderCancelledPayload
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_message_from_orderbook_proto_init() }
func file_message_from_orderbook_proto_init() {
	if File_message_from_orderbook_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_from_orderbook_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BidAsk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DepthPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OpenOrdersPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*OrderCompletedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Fills); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*OrderCancelledPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DepthMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*OpenOrdersMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*OrderCompletedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*OrderCancelledMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_from_orderbook_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*MessageFromOrderBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_from_orderbook_proto_msgTypes[10].OneofWrappers = []any{
		(*MessageFromOrderBook_DepthPayload)(nil),
		(*MessageFromOrderBook_OpenOrdersPayload)(nil),
		(*MessageFromOrderBook_OrderCompletedPayload)(nil),
		(*MessageFromOrderBook_OrderCancelledPayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_from_orderbook_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_from_orderbook_proto_goTypes,
		DependencyIndexes: file_message_from_orderbook_proto_depIdxs,
		EnumInfos:         file_message_from_orderbook_proto_enumTypes,
		MessageInfos:      file_message_from_orderbook_proto_msgTypes,
	}.Build()
	File_message_from_orderbook_proto = out.File
	file_message_from_orderbook_proto_rawDesc = nil
	file_message_from_orderbook_proto_goTypes = nil
	file_message_from_orderbook_proto_depIdxs = nil
}
